### ISSUE TITLE
Recommends from bfasilva

### ISSUE THREAD

**Issue by carl24k** [carl24k/fight-churn#16]
bfasilva: Hello Carl, hope you had a nice weekend. Just through your github repo and run the installation. 3 notes that may be useful to change to make the default values work seamless:
bfasilva: 1) The requirements.txt does not play well with the latest Python version (3.9). After installing 3.7 and using it for the project, it worked like a charm
bfasilva: 2) On metric_framework/conf the configuration file socialnet6_metrics.json can be renamed socialnet7_metrics.json
bfasilva: 3) Inside observe_churn.py, defaults starting on line 44 could be changed to: line
bfasilva: schema: churnsim2 -> socialnet7,
bfasilva: frdt: 2019-03-04 -> 2020-01-01
bfasilva: tode: 2019-05-06 -> 2020-01-08
bfasilva: The framework is looking great, thanks!
bfasilva: Have a nice week!

**Comment by seismatica** [comment]
Great tips! Thank you bfasilva :)

**Comment by carl24k** [comment]
Made these fixes.
