### ISSUE TITLE
Path for saved output is outside of repo

### ISSUE THREAD

**Issue by seismatica** [carl24k/fight-churn#17]
https://github.com/carl24k/fight-churn/blob/90cfa3b5b0f8ee721095875b70efb4dfba2fd684/listings/py/run_churn_listing.py#L124

I'm not sure if this is intended, but the path for output files (e.g. CSV) are outside of the repo folder (fight-churn), if the `../../../` relative path is used. If this is expected behavior, could you please help me understand the benefit of this approach? Thank you!

**Comment by carl24k** [comment]
I intended it to be parallel to the repo, not in the repo. (So fight-churn-output is next to where ever you put fight-churn.) Thats my personal preference. You could put it in the repo by changing those paths, and add that to your gitignore if that is your preference. Probably I should have made it an environment variable - maybe I'll do that. What would you have preffered?

**Comment by seismatica** [comment]
Either way is fine for me :) I'm not well versed in project structure myself so if you have any tips on that I'd be more than happy to learn.

**Comment by carl24k** [comment]
Well TBH I'm better at science than programming best practices. But I generally put my results outside of the repo folder, and just code and configurations in the repo folder.

**Comment by carl24k** [comment]
Nothing to do here.
