### ISSUE TITLE
ModuleNotFoundError: No module named 'listing_3_7_metric_qa_plot'

### ISSUE THREAD

**Issue by jtowler** [carl24k/fight-churn#20]
I ran into an issue in when running listing 3.7, specifically PyCharm could not find the the module `listing_3_7_metric_qa_plot.py`. 
This was easily fixed by marking the `listings/chap3` directory as sources root, but this directory did not appear in the list of directories in section 1.2.2.1 of the readme.

**Comment by carl24k** [comment]
Hi, thanks for pointing this out! I fixed it in a recent commit. I added the python script in that chapter near the end of development and missed this.
