### ISSUE TITLE
Can not create schema

### ISSUE THREAD

**Issue by jyk** [carl24k/fight-churn#22]
I can not create schema (https://github.com/carl24k/fight-churn#createdb 1.3.1 Schema Creation)
It gives error:
![image](https://user-images.githubusercontent.com/1227446/129860192-0578b693-00e1-4910-94e5-53e64e83025b.png)

**Comment by carl24k** [comment]
Hi, it looks like the Python moduels are not installed (or at least the postgres one  is not.)  You can see Pycharm is underlining your import statement in red.  If you open requirements.txt, it should offer to install the requirements for you. Or did you already do that?

**Comment by jyk** [comment]
Thanks, forgot to install packages. You can close :)
