### ISSUE TITLE
How to deal with renewals and expired discounts in subscription database

### ISSUE THREAD

**Issue by franzoni315** [carl24k/fight-churn#26]
I am implementing the metrics taught in the book, and I am very satisfied with the fact that the book covers complex cases, through which my company goes. However, although mentioned in the book, I think it does not teach how to deal with subscriptions that start with an initial discount, but the full price will be charged in the next renewal cycle. The problem that I see here is that the MRR changes for the same subscription and the net retention calculus would be compromised.

In my opinion, the way to overcome this issue is to split the subscription into several subscriptions that have their own MRR. Something like this:

Initial example:

- subscription_id: 1
- account_id: 1
- product_id: 1
- start_date: 2021-10-01
- end_date: None (still active)
- mrr: 10 (with discount) but full price is 20

After split:

First subscription:
- subscription_id: 1_1
- account_id: 1
- product_id: 1
- start_date: 2021-10-01
- end_date: 2021-11-01
- mrr: 10

Second subscription:
- subscription_id: 1_2
- account_id: 1
- product_id: 1
- start_date: 2021-11-01
- end_date: None (still active)
- mrr: 20

Is this the best solution for this problem?

**Comment by carl24k** [comment]
I think that make sense.The code I wrote is meant to work with co-terminal subscriptions generally even if the MRR changes from month (even if they are overlapping.)  The exception to that is LTV which assumes constant MRR, but for the special case of a discount on the first period you can just subtract the discount from the LTV.

**Comment by carl24k** [comment]
Seems like no followup on this, so closing issue.
