### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by karthiks** [carl24k/fight-churn#3]
When I try executing the  `./run_churnsim.sh` from terminal within pycharm, following the setup procedures, I get a lot of errors towards the end. All of these errors shout out, "ModuleNotFoundError: No module named 'tkinter'". This package is not there in the requirements.txt.

Even when I tried to install this package from the pycharm's terminal like, `pip install tkinter`, I get the error like below:
```
Collecting tkinter
  Could not find a version that satisfies the requirement tkinter (from versions: )
No matching distribution found for tkinter
(venv) 
```

Developer Environment Details:
- Ubuntu OS
- venv setup per guidelines
- Python version is 3.7.5

This is a show stopper for trying out the code, isn't it? :(

**Comment by carl24k** [comment]
I seem to have tkinter installed in my venv, but I never installed it
explicitly. Apparently it is a dependency in another package. Which
function exactly is giving you the error?  Maybe we can figure out which of
my packages is trying to include it.

 Thanks for the fixes in the pull request by the way, haven't had a chance
to review it yet (I'm under deadline to finish the final manuscript...)

**Comment by karthiks** [comment]
Aside: No problem!, please take your time. The book came out really well and I sure would recommend it to my circle. You have set a high bar and I wish you big success in this endeavor of yours. The book subject is kickass and your efforts are commendable. While I'm so glad that I got the opportunity to review this book on the 3rd round as well, I only wish I had time enough to spend more time to peruse through the book in entirety which I couldn't :(

@carl24k, There can't be differences in the generated/implicit library dependencies. Our single source of truth has to be the `requirements.txt` file. The purpose of virtual environments is lost otherwise right? And so I think, it is much easier to test this by creating a new `virtualenv` and doing a `pip install` in that env to see if it installs `tkinter` dependency. Maybe similar to something like below script (as in Ubuntu OS):
```shell
python3 -m venv env2test
source activate env2test
pip install -r requirements.txt
pip list | grep tkinter
```

Further, the script `./run_churnsim.sh` took a lot of time in my laptop to execute (I think 4-6 hours and not some 10-15 minutes as stated somewhere in the book). This is just FYI. I don't want to try running this one again :-/

P.S: I'm using `Python 3.7.5` and ideally this shouldn't make any difference to this issue.

P.S: There are a few more stuff which I hope to send across as pull request sooner.

Keep rocking!!..

**Comment by carl24k** [comment]
Hi Karthik, did you ever find out anything else about this module issue? Were you able to run the code? I haven't heard of this issue from anyone else. Thanks! And thanks for your other contributions, which I finally followed up on 👍

**Comment by carl24k** [comment]
Noone else seems to have this issue.
