### ISSUE TITLE
Module has no attribute error

### ISSUE THREAD

**Issue by nandakumar92** [carl24k/fight-churn#33]
Hi,

I am trying to run the churn listing function. I successfully installed fightchurn package in a virtual environment. After that I can also import run_churn_listing. But when I run set_churn_environment it is not able to find the function. Am I running it the right way? Adding screenshot for reference.

![image](https://user-images.githubusercontent.com/28901283/165188600-6cb2e67f-1a5e-4e17-9780-6a83cfbc376a.png)

**Comment by carl24k** [comment]
Hi, that looks right. I don't see what is wrong with it.  Here it is for me:

```
>>> from fightchurn import run_churn_listing
>>> run_churn_listing.set_churn_environment('churn','carl','churn','/Users/carl/churn_output/churn_output_2')
Setting Environment Variables user=carl for db=churn
```

Can you put the text of your console session in the issue, not just a screen shot? That might help.

**Comment by nandakumar92** [comment]
think something is wrong with my mac. ill close this issue.
