### ISSUE TITLE
Failed Schema Installation

### ISSUE THREAD

**Issue by AlbertoOrdigoni** [carl24k/fight-churn#36]
Hi Carl,

I am having issues with installing the DB Schema in PyCharm.

`C:\Users\alberto.ordigoni\Downloads\fight-churn-master\venv\Scripts\python.exe C:/Users/alberto.ordigoni/Downloads/fight-churn-master/fight-churn-master/fightchurn/datagen/churndb.py
Traceback (most recent call last):
  File "C:\Users\alberto.ordigoni\Downloads\fight-churn-master\fight-churn-master\fightchurn\datagen\churndb.py", line 47, in <module>
    setup_churn_db(schema_name)
  File "C:\Users\alberto.ordigoni\Downloads\fight-churn-master\fight-churn-master\fightchurn\datagen\churndb.py", line 27, in setup_churn_db
    con_string = f"postgresql://{os.environ['CHURN_DB_HOST']}/{os.environ['CHURN_DB']}?user={os.environ['CHURN_DB_USER']}&password={os.environ['CHURN_DB_PASS']}"
  File "C:\Users\alberto.ordigoni\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CHURN_DB_HOST'

Process finished with exit code 1`

![image](https://user-images.githubusercontent.com/109776952/180352815-475bf324-a6f4-48b6-a912-bcc68258de36.png)

Could you please assist?

Thanks,
Alberto

**Comment by carl24k** [comment]
It looks like the environment variables are not set. There is some information about that in the readme.  But I though the CHURN_DB_HOST should be set by default. So I will look into this...

**Comment by AlbertoOrdigoni** [comment]
Thanks Carl, I set up the environment variables as per your instructions.

I used the default Postgres user name (postgres) and my database password for the login details. 

I also created an output folder and added it to the variables.

![image](https://user-images.githubusercontent.com/109776952/180740992-33fadff9-5688-41ca-9daa-95b77934a5af.png)

I got the same error message: 

![image](https://user-images.githubusercontent.com/109776952/180741448-0cc20d1a-6af6-4d00-a855-3c2d4f4a07a0.png)

Am I doing something wrong here?

Thanks for your help,
Alberto

**Comment by carl24k** [comment]
Hi, this was my mistake: and I just pushed a fix. Can you re-pull the code and try it again? Backstory: I added an option to set the database host with the new environment variable, CHURN_DB_HOST. I made it backwards compatible when run from the package, but I forgot to make it backwards compatible when run with the script. Please let me know if the fix works. Sorry for the difficulty you had!

Best,
Carl

**Comment by AlbertoOrdigoni** [comment]
Hi Carl,

Thanks for looking into this, I downloaded the new code and I was able to create the schema in the database.

I am looking forward to going through the book chapters!

Thanks again,
Alberto
