### ISSUE TITLE
No listing for chapter 3 listing 5 in socialnet7_listings.json

### ISSUE THREAD

**Issue by nickv9** [carl24k/fight-churn#40]
When trying to run listing 3.5 using run_churn_listing.py an error is returned, "No listing for chapter 3 in socialnet7_listings.json"

I can see that there is no list5 item in the chap3 section of socialnet7_listings.json.

**Comment by carl24k** [comment]
Yes, listing 3.5 is not meant to be run on the simulated data  provided: it is as an example of what you would use if your events had real valued fields in them (like a monetary value in a transaction, or the duration of a viewing session in a media app.) But the simulated data does not have any field like that. There are some other examples like that: listing 3.14, 3.15 and 3.16 also show you things you could do if your data had the appropriate features; but its not meaningful (or even possible) to run them on the simulation. Let me know if you have any other questions.

**Comment by nickv9** [comment]
Oh yes, I see I missed that! Thank you for the quick response.
