### ISSUE TITLE
Redshift and Snowflake both don't support UNION with recursive CTE's

### ISSUE THREAD

**Issue by gghildyal-gearset** [carl24k/fight-churn#41]
The listing in chapter 4 to calculate churn periods don't work on Redshift and Snowflake as they don't support UNION, only UNION ALL. UNION ALL then runs into max_rows_recursion limits (only tried on Redshift) very quickly as it doesn't remove the duplicates from the previous run.

**Comment by carl24k** [comment]
Sorry for the slow reply. If your subscription data is clean you probably don't need to use the recursive algorithm. To replace listing 4.1 you could consider every currently active subscription as an "ongoing active period" starting at the subscription start date. To replace list 4.2, find every customer who has churned in the past and consider their last subscription as a churned period. You could also take all of their prior subscriptions (before the churn) as additional active periods. You would end up with a lot more records in your active periods table, but I think this might work out.

Have you found any more info about a technical workaround?

**Comment by gghildyal-gearset** [comment]
Thanks for the response. I will go through your response in a bit more detail after looking at 4.1 and 4.2 again, but I understand the gist of it here.

I didn't quite get a workaround from a technical perspective, but we had other data sources which pointed to active periods and churn periods, so was able to use that. Ideally I would like to do both just as a test to confirm the analysis from the two sources.

**Comment by gghildyal-gearset** [comment]
Closing the issue for now, firstly because I have a workaround and Carl has given me pointers to work around it using the subscriptions database as well.
