### ISSUE TITLE
Python Issue with Code Setup Stage

### ISSUE THREAD

**Issue by gchan1234** [carl24k/fight-churn#42]
Hi Carl! 

I recently bought your book and loving it so far, however I am having issues setting the relevant data. Currently at the Jupyter Notebook Setup stage and I am running into this error
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/14026632/229348420-0573390e-9c9f-4535-a5bb-a8fe2bc9d79a.png">

**Comment by carl24k** [comment]
I'm not quite sure. I'll try installing in a notebook - I haven't done that for a while.

**Comment by carl24k** [comment]
Closing this because of no followup.
